### ISSUE TITLE
De la balle :)

### ISSUE THREAD

**Issue by atinux** [IBM-Bluemix/openwhisk-publisher#1]
Juste pour dire que c'est super bien fait, je joue avec OpenWhisk depuis un moment et c'est exactement ce à quoi je pensais faire avec, merci pour ce super depot avec de supers explications !

**Comment by atinux** [comment]
Ping @l2fprod

**Comment by l2fprod** [comment]
merci :) your feedback on OpenWhisk is welcome too @Atinux !
