### ISSUE TITLE
Malformed request when running deploy script

### ISSUE THREAD

**Issue by greyhoundforty** [IBM-Bluemix/openwhisk-publisher#4]
When I run `./deploy.sh --install` I get the following error:

```
error: Unable to create rule 'publisher-github-rule': The request content was malformed:
requirement failed: The fully qualified name of the entity must contain at least the namespace and the name of the entity. (code 6803060)
Entities in namespace: default
```

Per [this](https://console.ng.bluemix.net/openwhisk/learn/cli) OpenWhisk documentation I have unset and reset my namespace. 

```
$ wsk namespace list
namespaces
tinylab_Production_US
```

**Comment by l2fprod** [comment]
@greyhoundforty

the obvious question: did you create the "local.env" file and set all the values in it?

then do you have the latest version of wsk command?

mine reads:

```
> wsk property get --cliversion
whisk CLI version	2017-03-11T20:11:54+00:00
```

and I don't have any issue with install.

**Comment by greyhoundforty** [comment]
This can be closed. The issue was that my wsk cli was out of date. After an update the deploy script worked as intended.
